#!/bin/bash
##PROCESS WORLDCLIM, GEBCO AND CROPLAND2005
date

set -o nounset  # Break if a variable is unset

# READ VARIABLES FROM CONFIGURATION FILE
SERVICEDIR="/globes/PROCESSING/WDPA/scripts/a0_servicefiles"
source ${SERVICEDIR}/wdpa_processing.conf

## Derived variables
((NTILES=${NCORES}-1))
LOCATION_LL_PATH=${DATABASE}/${LOCATION_LL}
PERMANENT_LL_MAPSET=${DATABASE}/${LOCATION_LL}"/PERMANENT"
BU_LIST_FILE=${SERVICEDIR}/${bu_list}.txt


## GRASS parallel processing block
((NTILES=${NCORES}-1))
((ALLBUS=$(cat ${BU_LIST_FILE} | wc -l)+1))
((TILESIZE=($ALLBUS+(${NCORES}-1))/${NCORES}))   #TILESIZE is rounded up in order to ensure that [last tile + TILESIZE] is always > ALLBUS" 
for TIL in $(for i in $(eval echo {0..$NTILES}); do ((start=${TILESIZE}*$i)); echo -n $start" "; done)
    do
    TIL=${TIL}
    TEMPORARY_MAPSET=tile_${TIL}
    TEMPORARY_MAPSET_PATH=${LOCATION_LL_PATH}/${TEMPORARY_MAPSET}
    #Build temporary Mapset name
    grass ${PERMANENT_LL_MAPSET} --exec g.mapset --q -c --overwrite mapset=${TEMPORARY_MAPSET}
    echo "./step8_clim_gebco_crop_bu.sh ${TIL} ${TEMPORARY_MAPSET_PATH} ${RESULTSPATH} ${TILESIZE} ${BU_LIST_FILE} ${BU_MAPSET}"
done | parallel -j ${NCORES} --joblog ${LOGPATH}/parallel_cont_1km_bu.log

echo "GRASS Processing completed, now post-processing results..."

## merge results
for MONTH in $(eval echo {01..12})
    do
    cat ${RESULTSPATH}/bu_prec_${MONTH}_tile*.csv >> ${RESULTSPATH}/bu_prec_${MONTH}.csv
    cat ${RESULTSPATH}/bu_tavg_${MONTH}_tile*.csv >> ${RESULTSPATH}/bu_tavg_${MONTH}.csv
    cat ${RESULTSPATH}/bu_tmax_${MONTH}_tile*.csv >> ${RESULTSPATH}/bu_tmax_${MONTH}.csv
    cat ${RESULTSPATH}/bu_tmin_${MONTH}_tile*.csv >> ${RESULTSPATH}/bu_tmin_${MONTH}.csv
done | parallel -j 12

cat ${RESULTSPATH}/bu_gebco_tile*.csv >> ${RESULTSPATH}/bu_gebco.csv

cat ${RESULTSPATH}/bu_cropland2005_tile*.csv >> ${RESULTSPATH}/bu_cropland2005.csv
wait

## delete mapsets and intermediate results
for TIL in $(for i in $(eval echo {0..$NTILES}); do ((start=${TILESIZE}*$i)); echo -n $start" "; done)
    do
    rm -rf ${LOCATION_LL_PATH}/tile_${TIL}
    rm -f ${RESULTSPATH}/*_tile${TIL}.csv
done

## SECOND CYCLE: REPEAT PROCESSING of WORLDCLIM, GEBCO AND CROPLAND FOR BUs NOT PROCESSED DURING FIRST CYCLE
cat ${RESULTSPATH}/bu_prec_01.csv | awk '{print $1}' FS="|">./cont_1km_actually_done.csv
comm -23 <(sort ${BU_LIST_FILE}) <(sort ./cont_1km_actually_done.csv)>./cont_1km_to_be_repeated.csv
MISSING_BU_LIST="cont_1km_to_be_repeated.csv"
for BU in $(cat ${MISSING_BU_LIST})
    do
    grass ${PERMANENT_LL_MAPSET} --exec ./dyn/process_cont_1km_${BU}.sh
done
for MONTH in $(eval echo {01..12})
    do
    cat ${RESULTSPATH}/bu_prec_${MONTH}_tile*.csv >> ${RESULTSPATH}/bu_prec_${MONTH}.csv
    cat ${RESULTSPATH}/bu_tavg_${MONTH}_tile*.csv >> ${RESULTSPATH}/bu_tavg_${MONTH}.csv
    cat ${RESULTSPATH}/bu_tmax_${MONTH}_tile*.csv >> ${RESULTSPATH}/bu_tmax_${MONTH}.csv
    cat ${RESULTSPATH}/bu_tmin_${MONTH}_tile*.csv >> ${RESULTSPATH}/bu_tmin_${MONTH}.csv
done

cat ${RESULTSPATH}/bu_gebco_tile*.csv >> ${RESULTSPATH}/bu_gebco.csv
cat ${RESULTSPATH}/bu_cropland2005_tile*.csv >> ${RESULTSPATH}/bu_cropland2005.csv

## REMOUVE INVALID VALUES FROM CSV GENERATED BY r.univar
for MONTH in $(eval echo {01..12})
    do
	sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/bu_prec_${MONTH}.csv
	mv ${RESULTSPATH}/bu_prec_${MONTH}.csv.bak ${RESULTSPATH}/bu_prec_${MONTH}.orig
	sed -i.bak 's/-nan/0/g' ${RESULTSPATH}/bu_prec_${MONTH}.csv

    sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/bu_tavg_${MONTH}.csv
	mv ${RESULTSPATH}/bu_tavg_${MONTH}.csv.bak ${RESULTSPATH}/bu_tavg_${MONTH}.orig
	sed -i.bak 's/-nan/0/g' ${RESULTSPATH}/bu_tavg_${MONTH}.csv

    sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/bu_tmax_${MONTH}.csv
	mv ${RESULTSPATH}/bu_tmax_${MONTH}.csv.bak ${RESULTSPATH}/bu_tmax_${MONTH}.orig
	sed -i.bak 's/-nan/0/g' ${RESULTSPATH}/bu_tmax_${MONTH}.csv

    sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/bu_tmin_${MONTH}.csv
	mv ${RESULTSPATH}/bu_tmin_${MONTH}.csv.bak ${RESULTSPATH}/bu_tmin_${MONTH}.orig
	sed -i.bak 's/-nan/0/g' ${RESULTSPATH}/bu_tmin_${MONTH}.csv
done

sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/bu_gebco.csv
mv ${RESULTSPATH}/bu_gebco.csv.bak ${RESULTSPATH}/bu_gebco.orig
sed -i.bak 's/-nan/0/g' ${RESULTSPATH}/bu_gebco.csv

sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/bu_cropland2005.csv
mv ${RESULTSPATH}/bu_cropland2005.csv.bak ${RESULTSPATH}/bu_cropland2005.orig
sed -i.bak 's/-nan/0/g' ${RESULTSPATH}/bu_cropland2005.csv

rm -f ${RESULTSPATH}/*.bak

echo "Post-processing completed, now cleaning intermediate results..."

## delete intermediate results
for TIL in $(for i in $(eval echo {0..$NTILES}); do ((start=${TILESIZE}*$i)); echo -n $start" "; done)
    do
    rm -f ${RESULTSPATH}/*_tile${TIL}.csv
done
rm -f ./*actually_done.csv
rm -f ./*to_be_repeated.csv

## delete dynamic scripts
rm -f dyn/process_cont_1km_*.sh

date
exit
